// frontend/src/components/dashboard/TopPayments.vue
<script setup lang="ts">
import type { PaymentRecord } from '@/types'
import { CURRENCY_SYMBOLS } from '@/types'
import { formatDateWithNext, daysUntil, getUrgencyClass } from '@/utils/formatDate'

interface Props {
  records: PaymentRecord[]
}

const props = defineProps<Props>()

function getIcon(direction: 'income' | 'expense') {
  return direction === 'income' ? '↗' : '↘'
}

function formatAmount(amount: number, currency: string) {
  const symbol = CURRENCY_SYMBOLS[currency as keyof typeof CURRENCY_SYMBOLS] || '¥'
  const formattedAmount = amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })
  return `${symbol}${formattedAmount}`
}
</script>

<template>
  <div class="bg-white rounded-2xl border border-gray-200 overflow-hidden">
    <div class="p-5 border-b border-gray-100 flex items-center justify-between">
      <div>
        <h2 class="font-bold text-gray-900">收付款 TOP 10</h2>
        <p class="text-gray-500 text-sm mt-0.5">按金额排序的重要交易</p>
      </div>
      <button class="text-sm text-blue-600 font-medium hover:text-blue-700">
        查看全部
      </button>
    </div>

    <div class="overflow-x-auto">
      <table class="w-full">
        <thead>
          <tr class="border-b border-gray-100">
            <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">交易</th>
            <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">类型</th>
            <th class="text-right py-3 px-4 text-sm font-medium text-gray-500">金额</th>
            <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">下次日期</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="record in records" :key="record.id" class="border-b border-gray-50 hover:bg-gray-50">
            <td class="py-3 px-4">
              <div class="flex items-center gap-3">
                <div class="w-8 h-8 rounded-full flex items-center justify-center text-sm"
                  :class="record.direction === 'income' ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'"
                >
                  {{ getIcon(record.direction) }}
                </div>
                <span class="font-medium text-gray-900">{{ record.name }}</span>
              </div>
            </td>
            <td class="py-3 px-4">
              <span :class="record.direction === 'income' ? 'text-green-600' : 'text-red-600'" class="font-medium text-sm">
                {{ record.direction === 'income' ? '收入' : '支出' }}
              </span>
            </td>
            <td class="py-3 px-4 text-right font-mono font-bold" :class="record.direction === 'income' ? 'text-green-600' : 'text-red-600'">
              {{ record.direction === 'income' ? '+' : '-' }}{{ formatAmount(record.amount, record.currency) }}
            </td>
            <td class="py-3 px-4 text-sm text-gray-500">
              <div class="flex items-center gap-2">
                <span class="w-2 h-2 rounded-full" :class="record.direction === 'income' ? 'bg-green-500' : 'bg-red-500'"></span>
                <span>{{ formatDateWithNext(record.next_occurrence || record.start_time) }}</span>
                <span
                  class="inline-block px-2 py-0.5 rounded-full text-xs font-medium border"
                  :class="getUrgencyClass(daysUntil(record.next_occurrence || record.start_time))"
                >
                  {{ daysUntil(record.next_occurrence || record.start_time) }} 天后
                </span>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
      
      <div v-if="records.length === 0" class="text-center py-8">
        <div class="text-5xl mb-4 opacity-30">📋</div>
        <p class="text-gray-500">暂无收付款记录</p>
        <button class="mt-4 px-4 py-2 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 transition-colors">添加第一条记录</button>
      </div>
    </div>
  </div>
</template>

// frontend/src/features/dashboard/components/top-payments.tsx
import { Link } from '@tanstack/react-router'
import { TrendingUp, TrendingDown } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import type { PaymentRecord } from '@/types'
import { formatAmount, daysUntil, getUrgencyClass, getUrgencyLabel } from '@/lib/format-date'

interface TopPaymentsProps {
  records: PaymentRecord[]
}

export function TopPayments({ records }: TopPaymentsProps) {
  if (records.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>金额 TOP</CardTitle>
          <CardDescription>按金额排序的收付款记录</CardDescription>
        </CardHeader>
        <CardContent>
          <div className='flex flex-col items-center justify-center py-8 text-center'>
            <p className='text-sm text-muted-foreground'>暂无收付款记录</p>
            <Link to='/create'>
              <Button variant='outline' size='sm' className='mt-3'>
                添加第一条记录
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>金额 TOP</CardTitle>
        <CardDescription>按金额排序的收付款记录</CardDescription>
      </CardHeader>
      <CardContent>
        <div className='space-y-3'>
          {records.map((record) => {
            const days = record.next_occurrence ? daysUntil(record.next_occurrence) : 999
            return (
              <Link
                key={record.id}
                to='/edit/$id'
                params={{ id: record.id }}
                className='flex items-center justify-between rounded-lg p-3 hover:bg-accent transition-colors'
              >
                <div className='flex items-center gap-3'>
                  <div className={`flex size-8 items-center justify-center rounded-full ${record.direction === 'income' ? 'bg-emerald-100 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-400' : 'bg-red-100 text-red-600 dark:bg-red-950 dark:text-red-400'}`}>
                    {record.direction === 'income' ? <TrendingUp className='size-4' /> : <TrendingDown className='size-4' />}
                  </div>
                  <div>
                    <p className='text-sm font-medium'>{record.name}</p>
                    <p className='text-xs text-muted-foreground'>{record.category || '未分类'}</p>
                  </div>
                </div>
                <div className='flex items-center gap-2'>
                  <div className='text-right'>
                    <p className={`text-sm font-semibold ${record.direction === 'income' ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400'}`}>
                      {record.direction === 'income' ? '+' : '-'}{formatAmount(record.amount, record.currency)}
                    </p>
                    {record.next_occurrence && (
                      <Badge variant='outline' className={`text-xs ${getUrgencyClass(days)}`}>
                        {getUrgencyLabel(days)}
                      </Badge>
                    )}
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      </CardContent>
    </Card>
  )
}
