// frontend/src/components/layout/mobile-nav.tsx
import { LayoutDashboard, CalendarDays, Plus, List, User } from 'lucide-react'
import { Link, useLocation } from '@tanstack/react-router'
import { cn } from '@/lib/utils'

const navItems = [
  { label: '概览', href: '/supcal', icon: LayoutDashboard },
  { label: '日历', href: '/supcal/calendar', icon: CalendarDays },
  { label: '记录', href: '/supcal/records', icon: List },
  { label: '我的', href: '/supcal/profile', icon: User },
]

export function MobileNav() {
  const location = useLocation()
  const pathname = location.pathname

  if (!pathname.startsWith('/supcal')) return null

  return (
    <nav className='fixed bottom-0 left-0 right-0 z-50 border-t bg-background md:hidden'>
      <div className='flex items-center justify-around px-2 py-1'>
        {navItems.slice(0, 2).map((tab) => {
          const Icon = tab.icon
          const isActive =
            tab.href === '/supcal'
              ? pathname === '/supcal'
              : pathname.startsWith(tab.href)

          return (
            <Link
              key={tab.href}
              to={tab.href}
              className={cn(
                'flex flex-col items-center gap-0.5 px-3 py-1.5 text-xs transition-colors',
                isActive ? 'text-primary' : 'text-muted-foreground'
              )}
            >
              <Icon className='h-5 w-5' />
              <span className='text-[10px] leading-tight'>{tab.label}</span>
            </Link>
          )
        })}

        <Link
          to='/supcal/create'
          className='flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg -mt-4'
        >
          <Plus className='h-6 w-6' />
        </Link>

        {navItems.slice(2).map((tab) => {
          const Icon = tab.icon
          const isActive = pathname.startsWith(tab.href)

          return (
            <Link
              key={tab.href}
              to={tab.href}
              className={cn(
                'flex flex-col items-center gap-0.5 px-3 py-1.5 text-xs transition-colors',
                isActive ? 'text-primary' : 'text-muted-foreground'
              )}
            >
              <Icon className='h-5 w-5' />
              <span className='text-[10px] leading-tight'>{tab.label}</span>
            </Link>
          )
        })}
      </div>
    </nav>
  )
}

// frontend-trash-01/src/components/layout/MobileNav.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

const navItems = [
  { path: '/', label: '首页', icon: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  { path: '/calendar', label: '日历', icon: 'M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z' },
  { path: '/records', label: '记录', icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01' },
  { path: '/profile', label: '我的', icon: 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z' },
  { path: '/create', label: '新建', icon: 'M12 4v16m8-8H4', isPrimary: true }
]

function isActive(path: string) {
  return route.path === path
}

function navigate(path: string) {
  router.push(path)
}
</script>

<template>
  <nav class="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 pb-safe md:hidden z-50">
    <div class="flex items-center justify-around h-16">
      <button
        v-for="item in navItems"
        :key="item.path"
        @click="navigate(item.path)"
        class="flex flex-col items-center justify-center w-16 h-full touch-manipulation"
        :class="{ 'text-blue-600': isActive(item.path) && !item.isPrimary, 'text-gray-400': !isActive(item.path) && !item.isPrimary }"
      >
        <template v-if="item.isPrimary">
          <div class="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center shadow-lg shadow-blue-600/30 -mt-4">
            <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="item.icon" />
            </svg>
          </div>
          <span class="text-xs mt-1 text-gray-600">{{ item.label }}</span>
        </template>
        <template v-else>
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="item.icon" />
          </svg>
          <span class="text-xs mt-1">{{ item.label }}</span>
        </template>
      </button>
    </div>
  </nav>
</template>
