// frontend-trash-02/src/components/forms/PaymentRecordForm.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowDownRight, ArrowUpRight, Loader2 } from 'lucide-react'
import { useRecordsStore } from '@/stores/records'
import { supportApi } from '@/services/api'
import { Combobox } from '@/components/ui/combobox'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import { SettingsRow, FormSectionHeader, InlineSegment } from '@/components/ui/settings-row'
import { CURRENCY_OPTIONS } from '@/types'
import type { PaymentRecordCreate, Category, PaymentMethod, PeriodType, Direction } from '@/types'
import { calculateEndTime } from '@/utils/formatDate'

const periods: { value: PeriodType; label: string }[] = [
  { value: 'week', label: '周' },
  { value: 'month', label: '月' },
  { value: 'quarter', label: '季度' },
  { value: 'half-year', label: '半年' },
  { value: 'year', label: '年' },
]

const directionOptions = [
  { value: 'income' as Direction, label: '收入', icon: <ArrowUpRight className="w-3.5 h-3.5" /> },
  { value: 'expense' as Direction, label: '支出', icon: <ArrowDownRight className="w-3.5 h-3.5" /> },
]

const inlineInputCls = "bg-transparent border-0 text-right text-sm font-medium w-full max-w-[180px] outline-none placeholder:text-muted-foreground/50 focus:ring-0"

export function PaymentRecordForm({ onSuccess }: { onSuccess: () => void }) {
  const router = useRouter()
  const { createPaymentRecord } = useRecordsStore()

  const [form, setForm] = useState<PaymentRecordCreate>({
    name: '',
    description: '',
    direction: 'expense',
    category: '',
    amount: 0,
    payment_method: '',
    period: 'month',
    start_time: new Date().toISOString().slice(0, 16),
    end_time: '',
    notes: '',
    currency: 'CNY',
  })

  const [categories, setCategories] = useState<Category[]>([])
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethod[]>([])
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [isLoadingData, setIsLoadingData] = useState(true)
  const [isEndTimeManuallySet, setIsEndTimeManuallySet] = useState(false)

  useEffect(() => {
    async function loadData() {
      try {
        const [cats, methods] = await Promise.all([
          supportApi.getCategories(),
          supportApi.getPaymentMethods(),
        ])
        setCategories(cats as Category[])
        setPaymentMethods(methods as PaymentMethod[])
      } catch (e) {
        console.error('Failed to load data:', e)
      } finally {
        setIsLoadingData(false)
      }
    }
    loadData()
  }, [])

  useEffect(() => {
    if (!isEndTimeManuallySet) {
      setForm((f) => ({
        ...f,
        end_time: calculateEndTime(f.start_time, f.period),
      }))
    }
  }, [form.start_time, form.period, isEndTimeManuallySet])

  async function handleSubmit() {
    if (!form.name.trim()) {
      setError('请输入名称')
      return
    }
    if (form.amount < 0) {
      setError('请输入有效金额')
      return
    }

    setError('')
    setIsSubmitting(true)

    try {
      await createPaymentRecord({
        ...form,
        description: form.description || undefined,
        end_time: form.end_time || undefined,
        notes: form.notes || undefined,
      })
      onSuccess()
    } catch (e) {
      setError(e instanceof Error ? e.message : '创建失败')
    } finally {
      setIsSubmitting(false)
    }
  }

  function resetForm() {
    setForm({
      name: '',
      description: '',
      direction: 'expense',
      category: '',
      amount: 0,
      payment_method: '',
      period: 'month',
      start_time: new Date().toISOString().slice(0, 16),
      end_time: '',
      notes: '',
      currency: 'CNY',
    })
    setIsEndTimeManuallySet(false)
    setForm((f) => ({
      ...f,
      end_time: calculateEndTime(f.start_time, f.period),
    }))
  }

  if (isLoadingData) {
    return (
      <div className="flex flex-col items-center justify-center py-16 gap-3">
        <Loader2 className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" />
        <p className="text-sm text-muted-foreground">加载数据中...</p>
      </div>
    )
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        handleSubmit()
      }}
    >
      {error && (
        <div className="px-4 py-3 mb-2 bg-destructive/10 border border-destructive/30 rounded-xl text-destructive text-sm">
          {error}
        </div>
      )}

      <div className="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <SettingsRow label="名称">
          <input
            type="text"
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
            placeholder="例如：房租、工资"
            className={inlineInputCls}
          />
        </SettingsRow>

        <SettingsRow label="流向">
          <InlineSegment
            options={directionOptions}
            value={form.direction}
            onChange={(v) => setForm({ ...form, direction: v })}
          />
        </SettingsRow>

        <SettingsRow label="金额">
          <div className="flex items-center gap-1">
            <span className="text-xs text-muted-foreground">¥</span>
            <input
              type="number"
              step="0.01"
              min="0"
              value={form.amount || ''}
              onChange={(e) => setForm({ ...form, amount: parseFloat(e.target.value) || 0 })}
              placeholder="0.00"
              className={inlineInputCls}
            />
          </div>
        </SettingsRow>

        <SettingsRow label="货币">
          <InlineSegment
            options={CURRENCY_OPTIONS.map((c) => ({
              value: c.value,
              label: `${c.symbol} ${c.label}`,
            }))}
            value={form.currency}
            onChange={(v) => setForm({ ...form, currency: v })}
          />
        </SettingsRow>

        <SettingsRow label="分类" showChevron>
          <Combobox
            value={form.category}
            onValueChange={(value) => setForm({ ...form, category: value })}
            items={categories.map((c) => c.name)}
            placeholder="选择分类"
          />
        </SettingsRow>

        <SettingsRow label="付款方式" showChevron>
          <Combobox
            value={form.payment_method}
            onValueChange={(value) => setForm({ ...form, payment_method: value })}
            items={paymentMethods.map((m) => m.name)}
            placeholder="选择付款方式"
          />
        </SettingsRow>
      </div>

      <FormSectionHeader>时间设置</FormSectionHeader>
      <div className="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <SettingsRow label="开始时间">
          <input
            type="datetime-local"
            value={form.start_time}
            onChange={(e) => setForm({ ...form, start_time: e.target.value })}
            className={inlineInputCls}
          />
        </SettingsRow>

        <SettingsRow label="结束时间">
          <div className="flex items-center gap-2">
            {!isEndTimeManuallySet && form.end_time && (
              <span className="text-[10px] text-green-600 dark:text-green-400 shrink-0">自动</span>
            )}
            <input
              type="datetime-local"
              value={form.end_time}
              onChange={(e) => {
                setForm({ ...form, end_time: e.target.value })
                setIsEndTimeManuallySet(true)
              }}
              className={inlineInputCls}
            />
          </div>
        </SettingsRow>
      </div>

      <FormSectionHeader>周期设置</FormSectionHeader>
      <div className="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <SettingsRow label="重复周期">
          <InlineSegment
            options={periods.map((p) => ({ value: p.value, label: p.label }))}
            value={form.period}
            onChange={(v) => setForm({ ...form, period: v })}
          />
        </SettingsRow>
      </div>

      <FormSectionHeader>更多详情</FormSectionHeader>
      <div className="rounded-xl bg-card ring-1 ring-foreground/10 overflow-hidden">
        <div className="flex items-start justify-between min-h-[48px] px-4 py-3 border-b border-border/40">
          <span className="text-sm text-foreground shrink-0 pt-0.5">备注</span>
          <Textarea
            value={form.notes}
            onChange={(e) => setForm({ ...form, notes: e.target.value })}
            placeholder="添加备注信息..."
            rows={2}
            className="border-0 bg-transparent text-right text-sm w-full max-w-[200px] resize-none p-0 focus-visible:ring-0"
          />
        </div>
      </div>

      <div className="flex gap-3 mt-6">
        <Button type="button" variant="outline" onClick={resetForm}>
          重置
        </Button>
        <Button type="submit" disabled={isSubmitting} className="flex-1">
          {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {isSubmitting ? '创建中...' : '创建记录'}
        </Button>
      </div>
    </form>
  )
}

// frontend/src/components/forms/PaymentRecordForm.vue
<script setup lang="ts">
import { ref, reactive, onMounted, computed } from 'vue'
import { useRecordsStore } from '@/stores/records'
import { api } from '@/services/api'
import ComboInput from '@/components/common/ComboInput.vue'
import type { PaymentRecordCreate, Category, PaymentMethod, PeriodType } from '@/types'
import { CURRENCY_OPTIONS } from '@/types'

const emit = defineEmits<{
  submit: []
}>()

const records = useRecordsStore()

const form = reactive<PaymentRecordCreate>({
  name: '',
  description: '',
  direction: 'expense',
  category: '',
  amount: 0,
  payment_method: '',
  period: 'month',
  start_time: new Date().toISOString().slice(0, 16),
  end_time: '',
  notes: '',
  currency: 'CNY',
})

const categories = ref<Category[]>([])
const paymentMethods = ref<PaymentMethod[]>([])
const isSubmitting = ref(false)
const error = ref('')
const isLoadingData = ref(true)

const periods: { value: PeriodType; label: string }[] = [
  { value: 'week', label: '周' },
  { value: 'month', label: '月' },
  { value: 'quarter', label: '季度' },
  { value: 'half-year', label: '半年' },
  { value: 'year', label: '年' },
]

const categoryOptions = computed(() => categories.value.map(c => c.name))
const paymentMethodOptions = computed(() => paymentMethods.value.map(m => m.name))

const isEndTimeManuallySet = ref(false)

function calculateEndTime(startTime: string, period: PeriodType): string {
  if (!startTime) return ''

  const startDate = new Date(startTime)
  const year = startDate.getFullYear()
  const month = startDate.getMonth()
  const date = startDate.getDate()

  const end = new Date(year, month, date)

  switch (period) {
    case 'week':
      end.setDate(end.getDate() + 7)
      break
    case 'month':
      end.setMonth(end.getMonth() + 1)
      break
    case 'quarter':
      end.setMonth(end.getMonth() + 3)
      break
    case 'half-year':
      end.setMonth(end.getMonth() + 6)
      break
    case 'year':
      end.setFullYear(end.getFullYear() + 1)
      break
  }

  const endYear = end.getFullYear()
  const endMonth = String(end.getMonth() + 1).padStart(2, '0')
  const endDate = String(end.getDate()).padStart(2, '0')

  return `${endYear}-${endMonth}-${endDate}T00:00`
}

function onEndTimeInput() {
  isEndTimeManuallySet.value = true
}

onMounted(async () => {
  try {
    const [cats, methods] = await Promise.all([
      api.get<Category[]>('/api/v1/support/categories'),
      api.get<PaymentMethod[]>('/api/v1/support/payment-methods'),
    ])
    categories.value = cats
    paymentMethods.value = methods
  } catch (e) {
    console.error('Failed to load data:', e)
  } finally {
    isLoadingData.value = false
  }
})

async function handleSubmit() {
  if (!form.name.trim()) {
    error.value = '请输入名称'
    return
  }
  if (form.amount < 0) {
    error.value = '请输入有效金额'
    return
  }

  error.value = ''
  isSubmitting.value = true
  
  try {
    await records.createPaymentRecord({
      ...form,
      description: form.description || undefined,
      end_time: form.end_time || undefined,
      notes: form.notes || undefined,
    })
    emit('submit')
    resetForm()
  } catch (e) {
    error.value = e instanceof Error ? e.message : '创建失败'
  } finally {
    isSubmitting.value = false
  }
}

function resetForm() {
  form.name = ''
  form.description = ''
  form.direction = 'expense'
  form.category = ''
  form.amount = 0
  form.payment_method = ''
  form.period = 'month'
  form.start_time = new Date().toISOString().slice(0, 16)
  form.end_time = ''
  form.notes = ''
  form.currency = 'CNY'
  isEndTimeManuallySet.value = false

  // 重置后自动计算结束时间
  form.end_time = calculateEndTime(form.start_time, form.period)
}
</script>

<template>
  <form @submit.prevent="handleSubmit" class="space-y-5">
    <div v-if="isLoadingData" class="text-center py-4">
      <div class="w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto"></div>
      <p class="text-sm text-gray-500 mt-2">加载数据中...</p>
    </div>
    
    <div v-if="error" class="p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">
      {{ error }}
    </div>
    
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        记录名称
      </label>
      <input
        v-model="form.name"
        type="text"
        placeholder="例如：房租、工资"
        class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all"
      />
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        类型
      </label>
      <div class="grid grid-cols-2 gap-3">
        <button
          type="button"
          @click="form.direction = 'income'"
          class="px-4 py-3 rounded-xl border-2 text-center font-medium transition-all flex items-center justify-center gap-2"
          :class="form.direction === 'income' 
            ? 'border-green-500 bg-green-50 text-green-600' 
            : 'border-gray-200 hover:border-gray-300 text-gray-700'"
        >
          <span class="text-xl">↗</span>
          收入
        </button>
        <button
          type="button"
          @click="form.direction = 'expense'"
          class="px-4 py-3 rounded-xl border-2 text-center font-medium transition-all flex items-center justify-center gap-2"
          :class="form.direction === 'expense' 
            ? 'border-red-500 bg-red-50 text-red-600' 
            : 'border-gray-200 hover:border-gray-300 text-gray-700'"
        >
          <span class="text-xl">↘</span>
          支出
        </button>
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        金额
      </label>
      <div class="relative">
        <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500 font-medium">¥</span>
        <input
          v-model.number="form.amount"
          type="number"
          step="0.01"
          min="0"
          placeholder="0.00"
          class="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all"
        />
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        货币类型
      </label>
      <div class="grid grid-cols-2 gap-3">
        <button
          v-for="currency in CURRENCY_OPTIONS"
          :key="currency.value"
          type="button"
          @click="form.currency = currency.value"
          class="px-4 py-3 rounded-xl border-2 text-center font-medium transition-all"
          :class="form.currency === currency.value
            ? 'border-blue-600 bg-blue-50 text-blue-600'
            : 'border-gray-200 hover:border-gray-300 text-gray-700'"
        >
          {{ currency.symbol }} {{ currency.label }}
        </button>
      </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          分类
        </label>
        <ComboInput
          v-model="form.category"
          :options="categoryOptions"
          placeholder="输入或选择分类"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          付款方式
        </label>
        <ComboInput
          v-model="form.payment_method"
          :options="paymentMethodOptions"
          placeholder="输入或选择付款方式"
        />
      </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          开始时间
        </label>
        <input
          v-model="form.start_time"
          type="datetime-local"
          class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all"
        />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          结束时间
          <span v-if="!isEndTimeManuallySet && form.end_time" class="text-xs text-green-600 ml-2">(自动计算)</span>
          <span v-else class="text-xs text-gray-400 ml-2">(可手动修改)</span>
        </label>
        <input
          v-model="form.end_time"
          @input="onEndTimeInput"
          type="datetime-local"
          class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all"
          :class="{ 'bg-green-50 border-green-200': !isEndTimeManuallySet && form.end_time }"
        />
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        重复周期
      </label>
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <button
          v-for="period in periods"
          :key="period.value"
          type="button"
          @click="form.period = period.value"
          class="px-4 py-3 rounded-xl border-2 text-center font-medium transition-all"
          :class="form.period === period.value 
            ? 'border-blue-600 bg-blue-50 text-blue-600' 
            : 'border-gray-200 hover:border-gray-300 text-gray-700'"
        >
          {{ period.label }}
        </button>
      </div>
    </div>

    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        备注（可选）
      </label>
      <textarea
        v-model="form.notes"
        placeholder="添加备注信息..."
        rows="3"
        class="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none transition-all resize-none"
      />
    </div>

    <div class="flex gap-3 pt-2">
      <button
        type="button"
        @click="resetForm"
        class="flex-1 px-4 py-3 border border-gray-200 rounded-xl font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        重置
      </button>
      <button
        type="submit"
        :disabled="isSubmitting"
        class="flex-1 px-4 py-3 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
      >
        <svg v-if="isSubmitting" class="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        {{ isSubmitting ? '创建中...' : '创建记录' }}
      </button>
    </div>
  </form>
</template>
