// frontend/src/components/calendar/DayRecords.vue
<script setup lang="ts">
import type { CalendarRecord, SimpleRecord, PaymentRecord } from '@/types'

interface Props {
  date: Date
  records: CalendarRecord[]
}

const props = defineProps<Props>()
const emit = defineEmits<{
  create: []
}>()

function formatDate(date: Date) {
  return date.toLocaleDateString('zh-CN', { 
    month: 'long', 
    day: 'numeric',
    weekday: 'short'
  })
}

function formatTime(dateStr: string) {
  const date = new Date(dateStr)
  return date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })
}

function getRecordIcon(record: CalendarRecord) {
  if (record.type === 'payment') {
    const r = record as PaymentRecord
    return r.direction === 'income' ? '↗' : '↘'
  }
  return '📅'
}

function getRecordColor(record: CalendarRecord) {
  if (record.type === 'payment') {
    const r = record as PaymentRecord
    return r.direction === 'income'
      ? 'bg-green-100 text-green-700'
      : 'bg-red-100 text-red-700'
  }
  return 'bg-blue-100 text-blue-600'
}

function getRecordAmount(record: CalendarRecord) {
  if (record.type === 'payment') {
    const r = record as PaymentRecord
    return (r.direction === 'income' ? '+' : '-') + '¥' + r.amount.toLocaleString()
  }
  return '提醒'
}

function sortedRecords() {
  return [...props.records].sort((a, b) => {
    const dateA = new Date(a.type === 'simple' ? (a as SimpleRecord).time : (a as PaymentRecord).start_time)
    const dateB = new Date(b.type === 'simple' ? (b as SimpleRecord).time : (b as PaymentRecord).start_time)
    return dateA.getTime() - dateB.getTime()
  })
}
</script>

<template>
  <div class="bg-white rounded-2xl border border-gray-200 overflow-hidden">
    <div class="p-5 border-b border-gray-100">
      <h3 class="font-bold text-gray-900">{{ formatDate(date) }}</h3>
      <p class="text-sm text-gray-500 mt-0.5">{{ records.length }} 条记录</p>
    </div>
    
    <div v-if="records.length === 0" class="p-8 text-center">
      <div class="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-3">
        <svg class="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </div>
      <p class="text-gray-500">这一天没有记录</p>
      <button 
        @click="emit('create')"
        class="mt-3 text-blue-600 font-medium hover:text-blue-700"
      >
        添加记录
      </button>
    </div>
    
    <div v-else class="divide-y divide-gray-100 max-h-96 overflow-y-auto">
      <div
        v-for="record in sortedRecords()"
        :key="record.id"
        class="p-4 flex items-center gap-3 hover:bg-gray-50 transition-colors"
      >
        <div 
          class="w-10 h-10 rounded-full flex items-center justify-center text-lg flex-shrink-0"
          :class="getRecordColor(record)"
        >
          {{ getRecordIcon(record) }}
        </div>
        
        <div class="flex-1 min-w-0">
          <p class="font-medium text-gray-900 truncate">{{ record.name }}</p>
          <p class="text-sm text-gray-500">
            {{ record.type === 'simple' 
              ? formatTime((record as SimpleRecord).time)
              : formatTime((record as PaymentRecord).start_time)
            }}
          </p>
        </div>
        
        <span 
          class="font-bold"
          :class="record.type === 'payment' && (record as PaymentRecord).direction === 'income' ? 'text-green-600' : 'text-gray-900'"
        >
          {{ getRecordAmount(record) }}
        </span>
      </div>
    </div>
  </div>
</template>

// frontend-trash-02/src/components/calendar/DayRecords.tsx
'use client'

import Link from 'next/link'
import { Calendar, Plus } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import type { CalendarRecord, SimpleRecord, PaymentRecord } from '@/types'
import { formatAmount, formatTime } from '@/utils/formatDate'

interface DayRecordsProps {
  date: Date
  records: CalendarRecord[]
}

function formatDate(date: Date) {
  return date.toLocaleDateString('zh-CN', {
    month: 'long',
    day: 'numeric',
    weekday: 'short',
  })
}

function getRecordIcon(record: CalendarRecord) {
  if (record.type === 'payment') {
    return (record as PaymentRecord).direction === 'income' ? '↗' : '↘'
  }
  return '📅'
}

function getRecordColor(record: CalendarRecord) {
  if (record.type === 'payment') {
    const r = record as PaymentRecord
    return r.direction === 'income' 
      ? 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-400' 
      : 'bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-400'
  }
  return 'bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-400'
}

function getRecordAmount(record: CalendarRecord) {
  if (record.type === 'payment') {
    const r = record as PaymentRecord
    return (r.direction === 'income' ? '+' : '-') + formatAmount(r.amount, r.currency || 'CNY')
  }
  return '提醒'
}

function sortedRecords(records: CalendarRecord[]) {
  return [...records].sort((a, b) => {
    const dateA = new Date(
      a.type === 'simple' ? (a as SimpleRecord).time : (a as PaymentRecord).start_time
    )
    const dateB = new Date(
      b.type === 'simple' ? (b as SimpleRecord).time : (b as PaymentRecord).start_time
    )
    return dateA.getTime() - dateB.getTime()
  })
}

export function DayRecords({ date, records }: DayRecordsProps) {
  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">{formatDate(date)}</CardTitle>
        <p className="text-sm text-muted-foreground">{records.length} 条记录</p>
      </CardHeader>

      {records.length === 0 ? (
        <CardContent className="pt-0">
          <div className="p-8 text-center">
            <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-3">
              <Calendar className="w-8 h-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground">这一天没有记录</p>
            <Link href="/create">
              <Button variant="link" className="mt-3">
                <Plus className="w-4 h-4 mr-1" />
                添加记录
              </Button>
            </Link>
          </div>
        </CardContent>
      ) : (
        <CardContent className="pt-0">
          <div className="divide-y divide-border -mx-6 px-6 max-h-96 overflow-y-auto">
            {sortedRecords(records).map((record) => (
              <div
                key={record.id}
                className="py-3 flex items-center gap-3 hover:bg-accent transition-colors -mx-6 px-6"
              >
                <div
                  className={cn(
                    "w-10 h-10 rounded-full flex items-center justify-center text-lg flex-shrink-0",
                    getRecordColor(record)
                  )}
                >
                  {getRecordIcon(record)}
                </div>

                <div className="flex-1 min-w-0">
                  <p className="font-medium truncate">{record.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {record.type === 'simple'
                      ? formatTime((record as SimpleRecord).time)
                      : formatTime((record as PaymentRecord).start_time)}
                  </p>
                </div>

                <span
                  className={cn(
                    "font-bold",
                    record.type === 'payment' && (record as PaymentRecord).direction === 'income'
                      ? 'text-green-600 dark:text-green-400'
                      : 'text-foreground'
                  )}
                >
                  {getRecordAmount(record)}
                </span>
              </div>
            ))}
          </div>
        </CardContent>
      )}
    </Card>
  )
}
